### ISSUE TITLE
*log-edit-files* buffer does not respect `display-buffer-alist` in `agitate-log-edit-informative-mode`

### ISSUE THREAD

**Issue by krisbalintona** [protesilaos/agitate#1]
I have `agitate-log-edit-informative-mode` enabled with `agitate-log-edit-informative-show-files` set to non-nil. I was trying to make the "\*log-edit-files\*" buffer non-selectable with `other-window` and to remove its modeline. The easiest way to do that was with `display-buffer-alist`:
``` emacs-lisp
(add-to-list 'display-buffer-alist
             `(,(rx (literal log-edit-files-buf)) ; Evaluates to "\\*log-edit-files\\*"
               (window-parameters . ((no-other-window . t)
                                     (mode-line-format . none)))))
```
However, for some reason this doesn't work (even with `switch-to-buffer-obey-display-actions` to non-nil). Some wonky behavior happens. At least for me, instead of a small files buffer appearing under the log-edit window, the log-edit window seems to be split vertically of equal size. I tried other `display-buffer-alist` changes and they produced different but unexpected results.

I am not sure if the issue is with log-edit's `log-edit-show-files` or with its implementation in agitate.

**Comment by protesilaos** [comment]
Hello Kristoffer!

> From: Kristoffer Balintona ***@***.***>
> Date: Fri, 20 Sep 2024 10:05:14 -0700
>
> I have `agitate-log-edit-informative-mode` enabled with
> `agitate-log-edit-informative-show-files` set to non-nil. I was trying
> to make the "\*log-edit-files\*" buffer non-selectable with
> `other-window` and to remove its modeline. The easiest way to do that
> was with `display-buffer-alist`:

Just to let you know that I read this and will try to reproduce it on
Sunday.

More to follow!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by krisbalintona** [comment]
Hey @protesilaos, I thought I should follow up with this.

**Comment by protesilaos** [comment]
> From: Kristoffer Balintona ***@***.***>
> Date: Wed, 18 Dec 2024 17:09:34 -0800
>
> Hey @protesilaos, I thought I should follow up with this.

Thank you! I will check it out right away.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
It seems this is an Emacs bug. I can reproduce it with the following code when I call Emacs from the command line with `emacs -Q`:

```elisp
(setq display-buffer-alist
      '(("\\*log-edit-files\\*"
         (window-parameters . ((no-other-window . t)
                               (mode-line-format . none))))))

(require 'vc)
(require 'log-edit)

(cvs-pop-to-buffer-same-frame
 (get-buffer-create log-edit-files-buf))
```

**Comment by krisbalintona** [comment]
Yes, I think you're right. Thank you for investigating. I think, then, it is appropriate to close this issue since the problem is not with agitate. Quickly glancing at the code responsible, it isn't obvious what changes should be made, especially considering backwards compatability.

I might decide to email emacs-devel about this in the future.
